Update utils

diff --git a/bin/utils b/bin/utils
--- a/bin/utils
+++ b/bin/utils
@@ -158,3 +158,266 @@ function to_install() {
 }
 
 #https://natelandau.com/bash-scripting-utilities/
+
+#!/usr/bin/env bash
+
+alias not='!'
+
+# convenience output functions
+
+function fatal {
+	printf "FATAL: ${*}\n"
+	exit 1
+}
+
+function fatal! {
+	>&2 printf "FATAL: ${*}\n"
+	exit 1
+}
+
+function error {
+	printf "ERROR: ${*}\n"
+}
+
+alias err=error
+
+function error! {
+	>&2 printf "ERROR: ${*}\n"
+}
+
+alias err!=error!
+
+function warn {
+	printf "WARNING: ${*}\n"
+}
+
+function warn! {
+	>&2 printf "WARNING: ${*}\n"
+}
+
+function info {
+	printf "INFO: ${*}\n"
+}
+
+function info! {
+	>&2 printf "INFO: ${*}\n"
+}
+
+# file/string checking functions
+
+function exists? {
+	[[ -e "${1}" ]]
+	return ${?}
+}
+
+function file? {
+	[[ -f "${1}" ]]
+	return ${?}
+}
+
+function directory? {
+	[[ -d "${1}" ]]
+	return ${?}
+}
+
+alias dir?=directory?
+
+function readable? {
+	[[ -r "${1}" ]]
+	return ${?}
+}
+
+alias read?=readable?
+
+function writeable? {
+	[[ -w "${1}" ]]
+	return ${?}
+}
+
+alias write?=writeable?
+
+function executable? {
+	[[ -x "${1}" ]]
+	return ${?}
+}
+
+alias exec?=executable?
+
+function empty? {
+	[[ -z "${1}" ]]
+	return ${?}
+}
+
+function nonempty? {
+	[[ -n "${1}" ]]
+	return ${?}
+}
+
+function number? {
+	case "${1}" in
+		''|*[!0-9]* ) return 1 ;;
+		* ) return 0 ;;
+	esac
+}
+
+# dependency/compatibility functions
+
+function installed? {
+	if empty? "${1}"; then
+		error! "${FUNCNAME[0]}: missing argument"
+		return 1
+	else
+		local cmd=$(command -v "${1}")
+
+		nonempty? "${cmd}" && file? "${cmd}"
+		return ${?}
+	fi
+}
+
+function require {
+	if empty? "{1}"; then
+		error! "${FUNCNAME[0]}: missing argument"
+	else
+		local func="__require_${1}"
+
+		if [[ $(type -t ${func}) != "function" ]]; then
+			error! "require: unknown requirement: ${1}"
+		else
+			${func}
+			return ${?}
+		fi
+	fi
+}
+
+function require! {
+	if empty? "${1}"; then
+		error! "${FUNCNAME[0]}: missing argument"
+		return 1
+	else
+		require "${1}" || (error! "unsatisfied requirement: ${1}" ; return 1)
+	fi
+}
+
+function __require_bash2 {
+	[[ "${BASH_VERSINFO[0]}" -eq 2 ]]
+	return ${?}
+}
+
+function __require_bash3 {
+	[[ "${BASH_VERSINFO[0]}" -eq 3 ]]
+	return ${?}
+}
+
+function __require_bash4 {
+	[[ "${BASH_VERSINFO[0]}" -eq 4 ]]
+	return ${?}
+}
+
+function __require_bash5 {
+	[[ "${BASH_VERSINFO[0]}" -eq 5 ]]
+	return ${?}
+}
+
+function __version_python {
+	local py_vers="python -c 'import sys; print(sys.version_info[0])'"
+	eval ${py_vers}
+}
+
+function __require_python {
+	installed? python
+	return ${?}
+}
+
+function __require_python2 {
+	installed? python2 || [[ $(__version_python) -eq 2 ]]
+	return ${?}
+}
+
+function __require_python3 {
+	installed? python3 || [[ $(__version_python) -eq 3 ]]
+	return ${1}
+}
+
+function __version_perl {
+	local pl_vers="perl -e 'print int($]);'"
+	eval ${pl_vers}
+}
+
+function __require_perl {
+	installed? perl
+	return ${?}
+}
+
+function __require_perl5 {
+	installed? perl && [[ $(__version_perl) -eq 5 ]]
+	return ${?}
+}
+
+function __version_ruby {
+	local rb_vers="ruby -e 'puts RUBY_VERSION[0..2]'"
+	eval ${rb_vers}
+}
+
+function __require_ruby {
+	installed? ruby
+	return ${?}
+}
+
+function __require_ruby18 {
+	installed? ruby1.8 || [[ $(__version_ruby) = "1.8" ]]
+	return ${?}
+}
+
+function __require_ruby19 {
+	installed? ruby1.9.1 || installed? ruby1.9.2 || installed? ruby1.9.3 || \
+		[[ $(__version_ruby) = "1.9" ]]
+	return ${?}
+}
+
+function __require_ruby20 {
+	installed? ruby2.0 || [[ $(__version_ruby) = "2.0" ]]
+	return ${?}
+}
+
+function __require_ruby21 {
+	installed? ruby2.1 || [[ $(__version_ruby) = "2.1" ]]
+	return ${?}
+}
+
+function __require_ruby22 {
+	installed? ruby2.2 || [[ $(__version_ruby) = "2.2" ]]
+	return ${?}
+}
+
+function __require_ruby23 {
+	installed? ruby2.3 || [[ $(__version_ruby) = "2.3" ]]
+	return ${?}
+}
+
+function __require_ruby24 {
+	installed? ruby2.4 || [[ $(__version_ruby) = "2.4" ]]
+	return ${?}
+}
+
+#Convenient output functions:
+#$ info "foo not found" # "INFO: foo not found"
+#$ error "foo not found" # "ERROR: foo not found"
+#$ warn "foo not found" # "WARNING: foo not found"
+#$ fatal "foo not found" # "FATAL: foo not found" and exits with $? 1
+
+#(Less) painful dependency/compatibility checking:
+#$ installed? jq || (error! "i need jq" && exit 1)
+#$ require bash4 || (error! "this script only works on bash 4 and above" && exit)
+
+#(Less) painful file and string checking:
+#$ exists? /etc/passwd && info "found /etc/passwd"
+#$ file? /usr || warn "not a regular file"
+#$ directory? /bin && info "found /bin"
+
+#$ readable? /var/log/syslog
+#$ writeable? ~/.bashrc
+#$ executable? /bin/ls
+
+#$ empty? "${foo}"
+#$ nonempty? "${foo}"
+
